name: Build Startup-Wiz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y debhelper dh-autoreconf libglib2.0-dev libgtk-3-dev libx11-dev intltool libpackagekit-glib2-dev dh-exec libsecret-1-dev libnm-dev libnma-dev

      - name: Autogen and configure
        run: |
          ./autogen.sh
          ./configure

      - name: Build
        run: |
          make clean
          make
          ls -lah */*
